---
- name: PlayBook desplegar la Aplicacion Web Teachers on Time
  hosts: teachers_on_time 
  become: true

  vars:

    - usuario_base_datos: admin_user_teachers_on_time
    - contrasena_usuario_base_datos: J88s1y6h%4we1NMYpI4
    - nombre_base_datos: teachers_on_time

  tasks:

    - name: Descargando Aplicacion Web Teachers on Time
      ansible.builtin.get_url:
        url: https://github.com/alejandroalsa/Teachers-on-Time/archive/refs/heads/master.zip
        dest: /var/www/html

    - name: Descomprimiendo Prestashop + añadiendo usuario www-data y grupo www-data
      ansible.builtin.unarchive:
        src: /var/www/html/Teachers-on-Time-master.zip
        dest: /var/www/html
        remote_src: true
        owner: www-data
        group: www-data

    - name: Borrando zip de Teachers on Time
      ansible.builtin.file:
        path: /var/www/html/Teachers-on-Time-master.zip
        state: absent

    - name: Borrando carpeta ansible de Teachers on Time
      ansible.builtin.file:
        path: /var/www/html/ansible
        state: absent

    - name: Borrando carpeta sql de Teachers on Time
      ansible.builtin.file:
        path: /var/www/html/sql
        state: absent

    - name: Reiniciando Apache2.4
      ansible.builtin.service:
        name: apache2.service
        state: restarted
