---
- name: PlayBook para instalacion de la pila LAMP
  hosts: time_control 
  become: true

  tasks:

    - name: Actualizndo los repositorios
      apt:
        update_cache: true

    - name: Descargando UNZIP
      apt:
        name: unzip
        state: present

    - name: Descargando codigo fuente de phpMyAdmin
      ansible.builtin.get_url:
        url: https://files.phpmyadmin.net/phpMyAdmin/5.2.0/phpMyAdmin-5.2.0-all-languages.zip
        dest: /tmp/

    - name: Descomprimiendo phpMyAdmin de /tmp
      unarchive:
        src:  /tmp/phpMyAdmin-5.2.0-all-languages.zip
        dest: /tmp/
        remote_src: true
    
    - name: EiliminaEliminando phpMyAdmin de /tmp
      file:
        path: /tmp/phpMyAdmin-5.2.0-all-languages.zip
        state: absent
    
    - name: Moviendo la carpeta de phpMyAdmin a /var/www/html/
      copy:
        src: /tmp/phpMyAdmin-5.2.0-all-languages/
        dest: /var/www/html/acceso_base_de_datos_time_control
        remote_src: true

    - name: Anadiendo usuario->www:web y grupo->www:web a /vars/www/html/acceso_base_de_datos_time_control
      file: 
        path: /vars/www/html/acceso_base_de_datos_time_control
        state: directory
        owner: www-data
        group: www-data
        recurse: true

    - name: Instalando el gestor de paquetes de Python3
      apt:
        name: python3-pip
        state: present

    - name: Instalando el modulo de pymysql
      pip:
        name: pymysql
        state: present
        
    - name: Reiniciando Apache2.4
      ansible.builtin.service:
        name: apache2.service
        state: restarted
